In [45]:
import pandas as pd


df_orders = pd.read_csv("data/super_store_us.xlsx - Orders .csv")
df_returns = pd.read_csv("data/super_store_us.xlsx - Returns.csv")
df_users = pd.read_csv("data/super_store_us.xlsx - Users.csv")

In [46]:
print("Orders:")
print(df_orders.head(5))

Orders:
   Row ID Order Priority  Discount  Unit Price  Shipping Cost  Customer ID  \
0   20847           High      0.01        2.84           0.93            3
1   20228  Not Specified      0.02      500.98          26.00            5
2   21776       Critical      0.06        9.48           7.29           11
3   24844         Medium      0.09       78.69          19.99           14
4   24846         Medium      0.08        3.28           2.31           14

       Customer Name       Ship Mode Customer Segment Product Category  ...  \
0      Bonnie Potter     Express Air        Corporate  Office Supplies  ...
1     Ronnie Proctor  Delivery Truck      Home Office        Furniture  ...
2      Marcus Dunlap     Regular Air      Home Office        Furniture  ...
3  Gwendolyn F Tyson     Regular Air   Small Business        Furniture  ...
4  Gwendolyn F Tyson     Regular Air   Small Business  Office Supplies  ...

    Region State or Province         City  Postal Code Order Date  Ship Date  \
0     West        Washington    Anacortes        98221   1/7/2015   1/8/2015
1     West        California  San Gabriel        91776  6/13/2015  6/15/2015
2     East        New Jersey      Roselle         7203  2/15/2015  2/17/2015
3  Central         Minnesota   Prior Lake        55372  5/12/2015  5/14/2015
4  Central         Minnesota   Prior Lake        55372  5/12/2015  5/13/2015

      Profit Quantity ordered new    Sales Order ID
0     4.5600                    4    13.01    88522
1  4390.3665                   12  6362.85    90193
2   -53.8096                   22   211.15    90192
3   803.4705                   16  1164.45    86838
4   -24.0300                    7    22.23    86838

[5 rows x 25 columns]

In [11]:
print("Returns:")
print(df_returns.head(5))

Returns:
   Order ID    Status
0        65  Returned
1       612  Returned
2       614  Returned
3       678  Returned
4       710  Returned

In [12]:
print("Users:")
print(df_users.head(5))

Users:
    Region  Manager
0  Central    Chris
1     East     Erin
2    South      Sam
3     West  William

In [47]:
df_orders.shape

(1952, 25)

In [15]:
df_returns.shape

(1634, 2)

In [16]:
df_users.shape

(4, 2)

In [48]:
df_orders.describe()

,Row ID,Discount,Unit Price,Shipping Cost,Customer ID,Product Base Margin,Postal Code,Profit,Quantity ordered new,Sales,Order ID
count,1952.000000,1952.000000,1952.000000,1952.000000,1952.000000,1936.000000,1952.000000,1952.000000,1952.000000,1952.000000,1952.000000
mean,19916.479508,0.048975,109.079221,12.968151,1735.376537,0.515186,51534.769467,114.793859,12.944672,985.828832,82365.924180
std,5957.595627,0.031378,393.481301,17.414631,991.078006,0.137055,29362.828420,1141.112387,13.871565,2559.900167,19042.295798
min,64.000000,0.000000,1.140000,0.490000,3.000000,0.350000,1001.000000,-16476.838000,1.000000,2.250000,359.000000
25%,19121.000000,0.020000,6.480000,3.230000,875.000000,0.380000,28560.000000,-84.485400,5.000000,58.807500,86767.750000
50%,21164.500000,0.050000,20.990000,6.150000,1738.000000,0.525000,48765.500000,1.476450,10.000000,202.395000,88376.000000
75%,23483.250000,0.080000,100.972500,14.362500,2578.250000,0.590000,78550.000000,116.201575,16.000000,802.945000,89957.000000
max,26389.000000,0.210000,6783.020000,164.730000,3403.000000,0.850000,99362.000000,9228.225600,167.000000,45737.330000,91586.000000

In [18]:
df_orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1952 entries, 0 to 1951
Data columns (total 25 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Row ID                1952 non-null   int64
 1   Order Priority        1952 non-null   object
 2   Discount              1952 non-null   float64
 3   Unit Price            1952 non-null   float64
 4   Shipping Cost         1952 non-null   float64
 5   Customer ID           1952 non-null   int64
 6   Customer Name         1952 non-null   object
 7   Ship Mode             1952 non-null   object
 8   Customer Segment      1952 non-null   object
 9   Product Category      1952 non-null   object
 10  Product Sub-Category  1952 non-null   object
 11  Product Container     1952 non-null   object
 12  Product Name          1952 non-null   object
 13  Product Base Margin   1936 non-null   float64
 14  Country               1952 non-null   object
 15  Region                1952 non-null   object
 16  State or Province     1952 non-null   object
 17  City                  1952 non-null   object
 18  Postal Code           1952 non-null   int64
 19  Order Date            1952 non-null   object
 20  Ship Date             1952 non-null   object
 21  Profit                1952 non-null   float64
 22  Quantity ordered new  1952 non-null   int64
 23  Sales                 1952 non-null   float64
 24  Order ID              1952 non-null   int64
dtypes: float64(6), int64(5), object(14)
memory usage: 381.4+ KB

In [19]:
df_orders["Order Priority"] = df_orders["Order Priority"].replace("Not Specified","None")


print(df_orders["Order Priority"].value_counts(dropna=False))

Low          398
None         396
High         391
Critical     390
Medium       376
Critical       1
Name: Order Priority, dtype: int64

In [ ]:
df_orders.head(100)

In [28]:
df_orders["Discount"] = df_orders["Discount"].apply(lambda x: f"{x:.0f}%")

In [29]:
df_orders.head(100)

,Row ID,Order Priority,Discount,Unit Price,Shipping Cost,Customer ID,Customer Name,Ship Mode,Customer Segment,Product Category,...,State or Province,City,Postal Code,Order Date,Ship Date,Profit,Quantity ordered new,Sales,Order ID,Discount_pct
0,20847,High,0%,2.84,0.93,3,Bonnie Potter,Express Air,Corporate,Office Supplies,...,Washington,Anacortes,98221,1/7/2015,1/8/2015,4.56000,4,13.01,88522,0%
1,20228,None,0%,500.98,26.00,5,Ronnie Proctor,Delivery Truck,Home Office,Furniture,...,California,San Gabriel,91776,6/13/2015,6/15/2015,4390.36650,12,6362.85,90193,0%
2,21776,Critical,0%,9.48,7.29,11,Marcus Dunlap,Regular Air,Home Office,Furniture,...,New Jersey,Roselle,7203,2/15/2015,2/17/2015,-53.80960,22,211.15,90192,0%
3,24844,Medium,0%,78.69,19.99,14,Gwendolyn F Tyson,Regular Air,Small Business,Furniture,...,Minnesota,Prior Lake,55372,5/12/2015,5/14/2015,803.47050,16,1164.45,86838,0%
4,24846,Medium,0%,3.28,2.31,14,Gwendolyn F Tyson,Regular Air,Small Business,Office Supplies,...,Minnesota,Prior Lake,55372,5/12/2015,5/13/2015,-24.03000,7,22.23,86838,0%
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,19315,Low,0%,43.22,16.71,169,Janice Cole,Regular Air,Corporate,Technology,...,Louisiana,Baton Rouge,70802,1/3/2015,1/5/2015,280.27458,3,130.62,87463,0%
96,19316,Low,0%,574.74,24.49,169,Janice Cole,Regular Air,Corporate,Technology,...,Louisiana,Baton Rouge,70802,1/3/2015,1/10/2015,-112.42630,12,6945.16,87463,0%
97,19317,Low,0%,10.14,2.27,169,Janice Cole,Regular Air,Corporate,Office Supplies,...,Louisiana,Baton Rouge,70802,1/3/2015,1/7/2015,24.92400,3,30.94,87463,0%
98,19314,Critical,0%,1.88,1.49,171,Christina Matthews,Regular Air,Corporate,Office Supplies,...,New Jersey,Fort Lee,7024,4/13/2015,4/15/2015,-2.90950,1,3.42,87464,0%
99,5361,Critical,0%,49.99,19.99,181,Wesley Waller,Regular Air,Small Business,Technology,...,California,San Francisco,94122,2/21/2015,2/21/2015,-76.89000,18,901.81,38087,0%

In [49]:
df_orders["Discount"] = (df_orders["Discount"] * 100).astype(int).astype(str) + '%'

In [50]:
df_orders.head(1000)

,Row ID,Order Priority,Discount,Unit Price,Shipping Cost,Customer ID,Customer Name,Ship Mode,Customer Segment,Product Category,...,Region,State or Province,City,Postal Code,Order Date,Ship Date,Profit,Quantity ordered new,Sales,Order ID
0,20847,High,1%,2.84,0.93,3,Bonnie Potter,Express Air,Corporate,Office Supplies,...,West,Washington,Anacortes,98221,1/7/2015,1/8/2015,4.56000,4,13.01,88522
1,20228,Not Specified,2%,500.98,26.00,5,Ronnie Proctor,Delivery Truck,Home Office,Furniture,...,West,California,San Gabriel,91776,6/13/2015,6/15/2015,4390.36650,12,6362.85,90193
2,21776,Critical,6%,9.48,7.29,11,Marcus Dunlap,Regular Air,Home Office,Furniture,...,East,New Jersey,Roselle,7203,2/15/2015,2/17/2015,-53.80960,22,211.15,90192
3,24844,Medium,9%,78.69,19.99,14,Gwendolyn F Tyson,Regular Air,Small Business,Furniture,...,Central,Minnesota,Prior Lake,55372,5/12/2015,5/14/2015,803.47050,16,1164.45,86838
4,24846,Medium,8%,3.28,2.31,14,Gwendolyn F Tyson,Regular Air,Small Business,Office Supplies,...,Central,Minnesota,Prior Lake,55372,5/12/2015,5/13/2015,-24.03000,7,22.23,86838
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,19826,Low,9%,12.95,4.98,1775,Marlene Kirk,Regular Air,Consumer,Office Supplies,...,Central,Indiana,South Bend,46614,6/14/2015,6/21/2015,123.89175,21,269.54,89944
996,20278,Not Specified,8%,5.78,5.67,1776,Charlotte Patterson,Regular Air,Consumer,Office Supplies,...,Central,Indiana,Terre Haute,47802,2/4/2015,2/5/2015,-53.89800,19,106.57,89941
997,20391,Low,7%,5.43,0.95,1777,Miriam Greenberg,Regular Air,Consumer,Office Supplies,...,Central,Indiana,Valparaiso,46383,4/22/2015,4/26/2015,26.50290,7,38.41,89939
998,21163,Low,2%,10.06,2.06,1777,Miriam Greenberg,Regular Air,Consumer,Office Supplies,...,Central,Indiana,Valparaiso,46383,1/3/2015,1/8/2015,90.62460,13,131.34,89940
999,20600,Not Specified,3%,19.99,11.17,1777,Miriam Greenberg,Regular Air,Corporate,Furniture,...,Central,Indiana,Valparaiso,46383,4/2/2015,4/3/2015,-20.87640,12,251.61,89942

In [52]:
df_orders["Unit Price"] = df_orders["Unit Price"].round(2)

In [54]:
df_orders.head(1000)

,Row ID,Order Priority,Discount,Unit Price,Shipping Cost,Customer ID,Customer Name,Ship Mode,Customer Segment,Product Category,...,Region,State or Province,City,Postal Code,Order Date,Ship Date,Profit,Quantity ordered new,Sales,Order ID
0,20847,High,1%,2.84,0.93,3,Bonnie Potter,Express Air,Corporate,Office Supplies,...,West,Washington,Anacortes,98221,1/7/2015,1/8/2015,4.56000,4,13.01,88522
1,20228,Not Specified,2%,500.98,26.00,5,Ronnie Proctor,Delivery Truck,Home Office,Furniture,...,West,California,San Gabriel,91776,6/13/2015,6/15/2015,4390.36650,12,6362.85,90193
2,21776,Critical,6%,9.48,7.29,11,Marcus Dunlap,Regular Air,Home Office,Furniture,...,East,New Jersey,Roselle,7203,2/15/2015,2/17/2015,-53.80960,22,211.15,90192
3,24844,Medium,9%,78.69,19.99,14,Gwendolyn F Tyson,Regular Air,Small Business,Furniture,...,Central,Minnesota,Prior Lake,55372,5/12/2015,5/14/2015,803.47050,16,1164.45,86838
4,24846,Medium,8%,3.28,2.31,14,Gwendolyn F Tyson,Regular Air,Small Business,Office Supplies,...,Central,Minnesota,Prior Lake,55372,5/12/2015,5/13/2015,-24.03000,7,22.23,86838
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,19826,Low,9%,12.95,4.98,1775,Marlene Kirk,Regular Air,Consumer,Office Supplies,...,Central,Indiana,South Bend,46614,6/14/2015,6/21/2015,123.89175,21,269.54,89944
996,20278,Not Specified,8%,5.78,5.67,1776,Charlotte Patterson,Regular Air,Consumer,Office Supplies,...,Central,Indiana,Terre Haute,47802,2/4/2015,2/5/2015,-53.89800,19,106.57,89941
997,20391,Low,7%,5.43,0.95,1777,Miriam Greenberg,Regular Air,Consumer,Office Supplies,...,Central,Indiana,Valparaiso,46383,4/22/2015,4/26/2015,26.50290,7,38.41,89939
998,21163,Low,2%,10.06,2.06,1777,Miriam Greenberg,Regular Air,Consumer,Office Supplies,...,Central,Indiana,Valparaiso,46383,1/3/2015,1/8/2015,90.62460,13,131.34,89940
999,20600,Not Specified,3%,19.99,11.17,1777,Miriam Greenberg,Regular Air,Corporate,Furniture,...,Central,Indiana,Valparaiso,46383,4/2/2015,4/3/2015,-20.87640,12,251.61,89942

In [56]:
df_orders["Shipping Cost"] = df_orders["Shipping Cost"].round(2)

In [57]:
df_orders.head(100)

,Row ID,Order Priority,Discount,Unit Price,Shipping Cost,Customer ID,Customer Name,Ship Mode,Customer Segment,Product Category,...,Region,State or Province,City,Postal Code,Order Date,Ship Date,Profit,Quantity ordered new,Sales,Order ID
0,20847,High,1%,2.84,0.93,3,Bonnie Potter,Express Air,Corporate,Office Supplies,...,West,Washington,Anacortes,98221,1/7/2015,1/8/2015,4.56000,4,13.01,88522
1,20228,Not Specified,2%,500.98,26.00,5,Ronnie Proctor,Delivery Truck,Home Office,Furniture,...,West,California,San Gabriel,91776,6/13/2015,6/15/2015,4390.36650,12,6362.85,90193
2,21776,Critical,6%,9.48,7.29,11,Marcus Dunlap,Regular Air,Home Office,Furniture,...,East,New Jersey,Roselle,7203,2/15/2015,2/17/2015,-53.80960,22,211.15,90192
3,24844,Medium,9%,78.69,19.99,14,Gwendolyn F Tyson,Regular Air,Small Business,Furniture,...,Central,Minnesota,Prior Lake,55372,5/12/2015,5/14/2015,803.47050,16,1164.45,86838
4,24846,Medium,8%,3.28,2.31,14,Gwendolyn F Tyson,Regular Air,Small Business,Office Supplies,...,Central,Minnesota,Prior Lake,55372,5/12/2015,5/13/2015,-24.03000,7,22.23,86838
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,19315,Low,8%,43.22,16.71,169,Janice Cole,Regular Air,Corporate,Technology,...,South,Louisiana,Baton Rouge,70802,1/3/2015,1/5/2015,280.27458,3,130.62,87463
96,19316,Low,5%,574.74,24.49,169,Janice Cole,Regular Air,Corporate,Technology,...,South,Louisiana,Baton Rouge,70802,1/3/2015,1/10/2015,-112.42630,12,6945.16,87463
97,19317,Low,4%,10.14,2.27,169,Janice Cole,Regular Air,Corporate,Office Supplies,...,South,Louisiana,Baton Rouge,70802,1/3/2015,1/7/2015,24.92400,3,30.94,87463
98,19314,Critical,5%,1.88,1.49,171,Christina Matthews,Regular Air,Corporate,Office Supplies,...,East,New Jersey,Fort Lee,7024,4/13/2015,4/15/2015,-2.90950,1,3.42,87464
99,5361,Critical,2%,49.99,19.99,181,Wesley Waller,Regular Air,Small Business,Technology,...,West,California,San Francisco,94122,2/21/2015,2/21/2015,-76.89000,18,901.81,38087